### ISSUE TITLE
Does not work with electron packager/asar archive 

### ISSUE THREAD

**Issue by ssrakesh** [auth0/jwt-decode#141]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Latest version 3.1.2 of this lib does not works with electron-packager, only 2.2.0

### Reproduction

-build a simple electron(v20.0.1) application.
-in main.js include 
const jwtDecode = require('jwt-decode');
-open the project/folder in vs code. press F5 to debug
-no issues

-include electron-packager(17.1.1) library
-build the project using this to make x64  exe
-run the exe
error reported
[2023-04-19 23:27:15.933] [error] App: Crash in Main:  Error: Cannot find module 'app.asar\node_modules\jwt-decode\build\jwt-decode.cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:360:19)
    at Module._findPath (node:internal/modules/cjs/loader:573:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (drive:\folder\main.js:12:32)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment
Windows x64

> Please provide the following:

- **Version of this library used:**  3.1.2
- **Version of the platform or framework used, if applicable:** electron(v20.0.1), electron-packager(17.1.1)
- **Other relevant versions (language, server software, OS, browser):** Windows x64
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Thanks. I think I can see what's going on. Any chance you have something to share that reproduces it to simplify debugging?

**Comment by ssrakesh** [comment]
just follow the same process as mentioned in main post.
Just create a 
-simple hello word electron app 
-include jwt-decode library in html page script and use with dummy data
and the issue can be reproduced.
However issue will not happen when entire electron project ES6 is enabled with type:"module"

**Comment by frederikprijck** [comment]
Im not familiar with electron or how you set it up. 

Good to know it works if u use es6! 

If you still need us to look into it, please elaborate why you can not set it to es6 and share a minimal reproduction and i am happy to look into it.

Thanks

**Comment by ssrakesh** [comment]
ok now we found it works with ES6, is there any reason for not working with normal js in asar mode?
Only older version v2.2.2 works in asar package.
reproduction steps mentioned above

**Comment by frederikprijck** [comment]
Thanks for the update. This package has not been tested with ASAR for electron. 

Can you elaborate what you mean when you say "normal js" ?

> reproduction steps mentioned above

As mentioned, we are not familiar with ASAR, so if you want us to help troubleshoot please provide a minimal reproduction of the issue for us to run and look into (e.g.  github repo).

Closing as it looks like it does work, happy to reopen if you have a reproduction of the issue that shows how the SDK does not work with ASAR.
